import type { Metadata } from "next";
import { fontInter, fontDrukCondensed, fontDrukTextWide, fontDrukText } from "@/public/fonts";
import "./globals.css";
import MaxWidthWrapper from "@/components/ui/MaxWidthWrapper";
import { NavBar } from "@/components/NavBar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontInter.variable} ${fontDrukCondensed.variable} ${fontDrukTextWide.variable} ${fontDrukText.variable} antialiased`}>
        <MaxWidthWrapper>
          <NavBar />
          {children}
        </MaxWidthWrapper>
        <Footer />
      </body>
    </html>
  );
}
