/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mecha.gltf --transform 
Files: mecha.gltf [54.88KB] > /home/crisppy-codes/Desktop/Pinterest UI Templates/anime-character-generator/public/3D/mecha-transformed.glb [764.46KB] (-1293%)
Author: Chenchanchong (https://sketchfab.com/Chenchanchong)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mecha-girl-warrior-a6a8b11defe647b38404fc6c3df50f01
Title: Mecha Girl Warrior
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/3D/mecha-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Wish_Meka_A} skeleton={nodes.Object_7.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.Wish_Meka_A_hair} skeleton={nodes.Object_8.skeleton} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/3D/mecha-transformed.glb')
